baseURL = "http://cecilialee.github.io/"
languageCode = "en-us"
title = "Cecilia Lee"
theme = "hugo-cactus-theme"

[params]
	name = "Cecilia Lee"
	description = "A Data Science Journal"
	bio = "A Data Science Journal"