baseurl = "https://cecilialee.github.io/"
languageCode = "en-us"
title = "Cecilia Lee"
theme = "cactus-plus"

[params]
	name = "Cecilia Lee"
	description = "A Data Science Journal"
	bio = "A Data Science Journal"